// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myndjssfrxmcwvxpvoci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15bmRqc3NmcnhtY3d2eHB2b2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzY0NjcsImV4cCI6MjA2OTIxMjQ2N30.q4lfAjeIkAAKwLhP8IwLfapIkACilPDiXaI2loCQcf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});